### ISSUE TITLE
Option for specifying only lower triangular part of A?

### ISSUE THREAD

**Issue by ajfriend** [oxfordcontrol/qdldl-python#4]
Would it be easy to add an option where the user needs to specify, for example, **only** the lower triangular part of `A`?

**Comment by bstellato** [comment]
Do you mean something like `lower_triangular=True`? In that case, it should not be hard.

**Comment by ajfriend** [comment]
Yeah, exactly!

**Comment by ajfriend** [comment]
Similar to https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.ldl.html

So that a user might save space in specifying the matrix.

**Comment by bstellato** [comment]
I have created a PR with `upper=True/False` option. QDLDL works only with the upper triangular part of `A` so this option removes the burden of extracting the upper triangular part internally.

**Comment by ajfriend** [comment]
Awesome. Thanks!
