### ISSUE TITLE
QDLDL silently fails when sizes are wrong

### ISSUE THREAD

**Issue by sbarratt** [oxfordcontrol/qdldl-python#6]
It seems like you can pass in a rhs to QDLDL that is not the right shape. Might be worth checking in python-world before solving.

Here's a minimum working example:
```
from scipy import sparse
import numpy as np
import qdldl

A = sparse.eye(10)
b = np.random.randn(8)

factor = qdldl.Solver(A)
print (factor.solve(b)) # evalutes to (...., 0, 0)
```

**Comment by bstellato** [comment]
Good catch. I will try to fix it in the next days.

I am already checking the dimensions of `A` via the pybind11 interface:

https://github.com/oxfordcontrol/qdldl-python/blob/master/cpp/wrapper.cpp#L56-L60

It should be easy to check the rhs dimension as well.
